run_mode: train           
task: cola
tokenizer: ipa
model: transformer
vocab_file: full.csv
max_len: 50
batch_size: 32
epochs: 40
lr: 0.00002054
patience: 10
dataset_path: data
checkpoint_path: best_model_cola_transformer1.pth
resume: false
